alexmingoia/koa-router

lib/router.js, package.json, test/lib/router.js
This is a basic implementation of the functionality requested in #105. You might be able to improve upon it, but I think this satisfies the main requirements.
**Update:**
Added ```Router#prefix``` as a convenience method.
=> Add support for path prefixes.

README.md
Took me 30 minutes to realize it, because `forums.get('/forums/:fid/posts', posts.routes())` will not match anything so I end up with a generic 404.
ref: https://github.com/alexmingoia/koa-router/blob/master/test/lib/router.js#L81
=> Fix typo in doc for nested router

lib/layer.js, lib/router.js
If route has a prefix and is in debug mode, the debug message will include prefix
```javascript
var koa = require('koa'),
r = require('koa-router')(),
app = koa();
r.prefix('/v1');
r.get('/users', ...);
app.use(r.routes());
....
```
*BEFORE*
```
koa-router defined route POST /users
```
*AFTER*
```
koa-router defined route POST /v1/users
```
=> Pass prefix to layer for debug printing route creation

.travis.yml, README.md, lib/layer.js, lib/router.js, package.json, test/lib/layer.js, test/lib/router.js
Opening this for discussion and thoughts:
I was messing with Koa 2 alpha 2 and needed a router — breaking changes around passing `ctx` as an argument yields `koa-router` unusable right now. There's another project [`ko66`](https://github.com/menems/koa-66) that seems to be a similar project that's been setup for Koa 2 support, but I'd like to see this lib grow and I'm sure others would as well.
This PR updates all middleware to the Promise-based Koa 2 async pattern. It does not use `async/await`notation or transpiling, which I could see being an options for this lib as well. For simplicity's sake, everything `GeneratorFunction` was changed to a function with promise-based flow, all middleware functions were updates to the `(ctx, next)` signature and `ctx` is now used in place of `this` …
=> updates for koa2.x, use compose for stacks

README.md, lib/router.js, test/lib/router.js
I have a need to throw my own objects in place of koa-router's default use of `HTTPError`. This PR adds two functions to the options object in `allowedMethods(options)`. The two new functions will be triggered when the `throw` option is true and if the functions are defined, otherwise the default `HTTPError`s are used.
Added tests and updated the README. Thanks!
=> Adding custom user-provided throw functions for "Not Implemented" and "Method Not Allowed"

lib/layer.js
`router.url()` was failing for me with complex parameters (optional, regex, etc) so I've updated it to utilize Path-to-RegExp's `compile` and `parse` methods. Tests are untouched and still passing.
=> Improved router.url().

test/lib/router.js
Because of changes introduced in 883c1aff (5.2.0+), in some cases, routes without any parameters receive incorrect parameter values regardless.
Example:
```
router.get('/notparameter', function *(next) {
// Problem: this.params.param shouldn't exist, but does.
});
router.get('/:param', function *(next) {
// this.params.param should exist. No problem here.
});
```
It's because of the way the code iterates when matching routes - caching captures and params from the previous iteration. I wasn't sure why it did that, so I created a failing test case instead. Hope it helps.
=> Nonexistent parameters passed when matching/dispatching routes

lib/router.js, test/lib/router.js
Expose the route that matched the current request on context. This is useful for monitoring and analytics, and enables you to do something like the following:
```javascript
function* routeMetrics(next) {
var start = Date.now()
yield next
var duration = Date.now() - start
// send a metric
statsd.timing(this._matchedRoute, duration)
// this.matchedRoute would be the string of the matched route, so '/foo/:id/:type/' in this case
}
```
This will send a count of the number of times a specific route is hit, even if the route has dynamic parts.
I'm happy to tweak this, change the name, or add more tests if you are ok with this basic idea.
I believe this fixes #223.
=> add _matchedRoute to context

lib/layer.js, lib/router.js, test/lib/router.js
fixes #247 for koa2 (master branch)
see #287
=> fix incorrect params with router.use(fn) (koa2)

lib/layer.js, test/lib/router.js
This fixes #237 by adjusting the way that param handlers are injected into the stack. Currently, the params handlers are added in the order in which you defined them, rather than the order they are defined in the URL.
I've added a few tests cases here to demonstrate the problem, as well as made the necessary changes to fix it. (all other tests are still passing)
Apologies for the weird PR, I actually started on this fix a couple of months ago, but then got sidetracked after a solution didn't come to mind easily. I picked it up again yesterday, and finally came up with something elegant. :)
=> Fix bug where param handlers were run out of order

lib/layer.js, lib/router.js, test/lib/router.js
This pull request fixes the extra params bug (#247) which occurs when middleware is `use`d without a path. Before this PR, `this.params[0]` is incorrectly set to the path of the matched route. After this PR, only the named parameters are set.
=> fix incorrect params with router.use(fn)

lib/router.js, test/lib/router.js
sometimes route paths can be very long & convoluted (legacy apis), exposing the layer
name provides a saner alternative for analytics
this is an extension to #236 
/cc @alexmingoia @jergason
=> add `_matchedRouteName` to context

.travis.yml, lib/layer.js, lib/router.js, test/lib/router.js
I tried to fixed a bug found within **Router#url under the latest version**, where I get errors when trying to get a url with a name provided in an embedded router middleware, the change doesn't affect other parts(at least all test is passed :b ).
Also I find that in Koa2 you cannot access router object as previous version, where you can use:
```javascript
router.get('book-detail', '/books/:book_id', function *() {
// some code...
});
router.post('create-book', '/books', function *() {
// some code...
this.redirect(this.app.url('book-detail', {book_id: book.id}));
});
```
So I append the router object to ctx. This leads to the following usage:
```javascript
router.get('book-detail', '/books/:book_id', function (ctx) {
// some code...
});
router.post('create-book', '/books', function (ctx) …
```
=> Fix a bug in Router#url & append Router object to ctx.

lib/router.js, package.json, test/lib/router.js
we can't mixed promise base middleware with generator base middleware, the execute order will change.
```js
function* generatorMiddleware() {
console.log('step 1');
yield next;
console.log('step 3');
}
async function asyncMiddleware() {
console.log('step 2');
}
router.get('/', generatorMiddleware, asyncMiddleware);
```
The result will be `2 => 1 => 3` instead of `1 => 2 => 3`.
This PR fix this issue by convert async function to generator function with `co`.
=> fix promise middleware

lib/router.js, test/lib/router.js
> When an options request is made to an app using koa-router, multiple "Allow" headers are set instead of one header with a comma separated value.
> For example, I've got a route that currently only supports GET requests. When I ping it with an OPTIONS request, it should attach a header like:
```
Allow: HEAD, GET
```
> but instead if I inspect the response headers with chrome dev tools, I get
```
Allow: HEAD
Allow: GET
```
RFC isn't super clear about having several of these headers. Node
happens to parse them as a single comma-separated list, but this
behavior isn't the same in all programs. This should be non-breaking for
almost all applications and fixes an issue in #273
https://tools.ietf.org/html/rfc7231#section-7.4.1
fixes #273
=> Comma-separate list of Allow header methods (#273)

README.md, lib/router.js
There are `sensitive`, `strict` and `methods` options which the router accepts, but are currently undocumented.
I've added the missing `strict` option to the TypeScript type definition too in DefinitelyTyped/DefinitelyTyped#21250 (`sensitive` and `methods` are already documented).
I re-generated the README using `npm run docs`, but it looks like it changed a lot of stuff. Should I just keep the changes which refer to the new options?
=> Add documentation for missing options

README.md
The current example would end the request prematurely.
=> fix(readme): return next()

README.md, lib/layer.js, package.json, test/lib/router.js
From "Add query parameters argument to Router.prototype.url method" #227 discussion
| Param | Type | Description |
| --- | --- | --- |
| name | <code>String</code> | route name |
| params | <code>Object</code> | url parameters |
| [options] | <code>Object</code> | options parameter |
| [options.query] | <code>Object</code> &#124; <code>String</code> | query options |
**Example**  
```javascript
router.url('user', { id: 3 }, { query: { limit: 1 } });
// => "/users/3?limit=1"
router.url('user', { id: 3 }, { query: "limit=1" });
// => "/users/3?limit=1"
```
=> Feature: Router#url() accepts extra query parameters as options

lib/layer.js, test/lib/router.js
fixes #351 by replacing all (.*) in the path, not just the first one.
=> Fix router.url() for multiple nested routers

lib/router.js, test/lib/router.js
Fixes what looks like a regression in 8665620 in which `path` inside of
`.use()` is defaulted to a wildcard `(.*)` instead of remaining
undefined while the line:
```js
if (path) nestedLayer.setPrefix(path)
```
runs. Where previously the line:
```js
var path;
```
resulted in no `setPrefix` call the current code (`var path = '(.*)';`) _does_ allow `setPrefix` to be called on the nested layer and creates erroneous wildcard suffixes to route segments.
https://github.com/alexmingoia/koa-router/blob/840591d4f660ddde98aedc689dea862a7e63f55b/lib/router.js#L265
This fixes #369 and #410
A test case has been added.
=> remove default wildcard prefix for nested routers
